# Generated by Django 3.2.25 on 2024-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_full_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_ordernumber', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_issue', models.CharField(choices=[('choices', 'Choose an Issue (optional)'), ('order', 'Something is wrong with my Order.'), ('collaboration', 'I / We want to collaborate with NEW YORK COLA.'), ('product', 'I have a question about the product.')], default='choices', max_length=100)),
                ('contact_message', models.TextField(max_length=500)),
            ],
        ),
    ]
